class StaticData {
  // قائمة المهارات (Skills) الكاملة
  static const List<Map<String, dynamic>> initialSkills = [
    // Group 1: مهارات دقيقة وبناء (Fine Motor & Construction)
    {'skill_group': 'مهارات دقيقة وبناء', 'skill_description': 'مدّ اليد والإمساك بالأشياء لوضعها في الفم', 'min_age_months': 6},
    {'skill_group': 'مهارات دقيقة وبناء', 'skill_description': 'التحكم في ترك الأشياء بإرادة', 'min_age_months': 6},
    {'skill_group': 'مهارات دقيقة وبناء', 'skill_description': 'التقاط الأشياء الصغيرة بين الإبهام وأصبع واحد', 'min_age_months': 6},
    {'skill_group': 'مهارات دقيقة وبناء', 'skill_description': 'نقل الأشياء من يد إلى أخرى', 'min_age_months': 6},
    {'skill_group': 'مهارات دقيقة وبناء', 'skill_description': 'ضرب مكعبين معًا في منتصف الجسم', 'min_age_months': 6},
    {'skill_group': 'مهارات دقيقة وبناء', 'skill_description': 'الإشارة أو النقر بإصبع السبابة', 'min_age_months': 6},
    {'skill_group': 'مهارات دقيقة وبناء', 'skill_description': 'استعادة الأشياء الساقطة...', 'min_age_months': 6},
    {'skill_group': 'مهارات دقيقة وبناء', 'skill_description': 'بناء برج من ثلاث مكعبات صغيرة', 'min_age_months': 12},
    {'skill_group': 'مهارات دقيقة وبناء', 'skill_description': 'وضع الحلقات على العصا', 'min_age_months': 12},
    {'skill_group': 'مهارات دقيقة وبناء', 'skill_description': 'تقليب صفحات الكتاب (صفحتين أو ثلاث معًا)', 'min_age_months': 12},
    {'skill_group': 'مهارات دقيقة وبناء', 'skill_description': 'إدارة المقابض', 'min_age_months': 12},
    {'skill_group': 'مهارات دقيقة وبناء', 'skill_description': 'استخدام الإشارات للتعبير عن الاحتياجات', 'min_age_months': 12},
    {'skill_group': 'مهارات دقيقة وبناء', 'skill_description': 'وضع الأشكال في صندوق الأشكال بدون مساعدة', 'min_age_months': 12},
    {'skill_group': 'مهارات دقيقة وبناء', 'skill_description': 'تركيب 3 - 4 خرزات كبيرة في خيط', 'min_age_months': 24},
    {'skill_group': 'مهارات دقيقة وبناء', 'skill_description': 'بناء برج من 3 - 5 مكعبات صغيرة', 'min_age_months': 24},
    {'skill_group': 'مهارات دقيقة وبناء', 'skill_description': 'تقليد ترتيب بسيط من مكعبات ملونة في برج', 'min_age_months': 24},
    {'skill_group': 'مهارات دقيقة وبناء', 'skill_description': 'تقليب صفحات الكتاب صفحة صفحة', 'min_age_months': 24},
    {'skill_group': 'مهارات دقيقة وبناء', 'skill_description': 'استخدام يد واحدة بشكل ثابت لمعظم الأنشطة', 'min_age_months': 24},
    {'skill_group': 'مهارات دقيقة وبناء', 'skill_description': 'إكمال ألعاب إدخال القطع (puzzles)', 'min_age_months': 24},
    {'skill_group': 'مهارات دقيقة وبناء', 'skill_description': 'بناء برج من حوالي 9 مكعبات صغيرة', 'min_age_months': 36},
    {'skill_group': 'مهارات دقيقة وبناء', 'skill_description': 'تقليد تصميم من 6 مكعبات', 'min_age_months': 36},
    {'skill_group': 'مهارات دقيقة وبناء', 'skill_description': 'استخدام يد واحدة باستمرار لمعظم الأنشطة', 'min_age_months': 36},
    {'skill_group': 'مهارات دقيقة وبناء', 'skill_description': 'استخدام اليد غير المسيطرة لتثبيت الأشياء', 'min_age_months': 36},
    {'skill_group': 'مهارات دقيقة وبناء', 'skill_description': 'تمرير خرزات صغيرة في خيط بترتيب', 'min_age_months': 36},
    {'skill_group': 'مهارات دقيقة وبناء', 'skill_description': 'إكمال ألعاب تركيب من 4 - 6 قطعة', 'min_age_months': 36},
    {'skill_group': 'مهارات دقيقة وبناء', 'skill_description': 'تقليد نماذج من 9 مكعبات', 'min_age_months': 48},
    {'skill_group': 'مهارات دقيقة وبناء', 'skill_description': 'تصميم نماذج من مكعبات Duplo', 'min_age_months': 48},
    {'skill_group': 'مهارات دقيقة وبناء', 'skill_description': 'استخدام يد مفضلة لمعظم الأنشطة', 'min_age_months': 48},
    {'skill_group': 'مهارات دقيقة وبناء', 'skill_description': 'نسخ صور بسيطة باستخدام الأشكال الهندسية', 'min_age_months': 48},
    {'skill_group': 'مهارات دقيقة وبناء', 'skill_description': 'رسم صور بسيطة بشكل مستقل', 'min_age_months': 48},
    {'skill_group': 'مهارات دقيقة وبناء', 'skill_description': 'إكمال ألعاب تركيب من 8 - 12 قطعة', 'min_age_months': 48},
    {'skill_group': 'مهارات دقيقة وبناء', 'skill_description': 'تصميم نماذج من مكعبات Lego', 'min_age_months': 60},
    {'skill_group': 'مهارات دقيقة وبناء', 'skill_description': 'رسم صور بسيطة', 'min_age_months': 60},
    {'skill_group': 'مهارات دقيقة وبناء', 'skill_description': 'إكمال ألعاب تركيب من 20 قطعة', 'min_age_months': 60},
    {'skill_group': 'مهارات دقيقة وبناء', 'skill_description': 'بناء نماذج Lego أو K\'nex وغيرها', 'min_age_months': 72},
    {'skill_group': 'مهارات دقيقة وبناء', 'skill_description': 'رسم صور تفصيلية تحتوي على عناصر واضحة', 'min_age_months': 72},
    {'skill_group': 'مهارات دقيقة وبناء', 'skill_description': 'إكمال ألعاب تركيب أكثر تعقيدًا', 'min_age_months': 84},
    {'skill_group': 'مهارات دقيقة وبناء', 'skill_description': 'رسم صور تفصيلية تحتوي على عناصر معروفة', 'min_age_months': 84},

    // Group 2: مهارات ما قبل الكتابة (Pre-Writing Skills)
    {'skill_group': 'مهارات ما قبل الكتابة', 'skill_description': 'التلوين بحركات الذراع الكاملة', 'min_age_months': 12},
    {'skill_group': 'مهارات ما قبل الكتابة', 'skill_description': 'مسك القلم بالإبهام والأصابع', 'min_age_months': 24},
    {'skill_group': 'مهارات ما قبل الكتابة', 'skill_description': 'تقليد رسم خطوط دائرية، رأسية وأفقية', 'min_age_months': 24},
    {'skill_group': 'مهارات ما قبل الكتابة', 'skill_description': 'التتبع على خطوط سميكة', 'min_age_months': 36},
    {'skill_group': 'مهارات ما قبل الكتابة', 'skill_description': 'نسخ دائرة أو تقليد رسم علامة (+)', 'min_age_months': 36},
    {'skill_group': 'مهارات ما قبل الكتابة', 'skill_description': 'مسك القلم بالإبهام والأصابع من الجانبين', 'min_age_months': 36},
    {'skill_group': 'مهارات ما قبل الكتابة', 'skill_description': 'نسخ دائرة، صليب، ومربع', 'min_age_months': 48},
    {'skill_group': 'مهارات ما قبل الكتابة', 'skill_description': 'مسك القلم بمسكة ثلاثية (3 أصابع)', 'min_age_months': 48},
    {'skill_group': 'مهارات ما قبل الكتابة', 'skill_description': 'التلوين داخل الخطوط', 'min_age_months': 48},
    {'skill_group': 'مهارات ما قبل الكتابة', 'skill_description': 'تلوين الصورة بالكاملكتابة الاسم', 'min_age_months': 48},
    {'skill_group': 'مهارات ما قبل الكتابة', 'skill_description': 'التتبع على خط بتحكم', 'min_age_months': 48},
    {'skill_group': 'مهارات ما قبل الكتابة', 'skill_description': 'نسخ الأرقام من 1 إلى 5', 'min_age_months': 48},
    {'skill_group': 'مهارات ما قبل الكتابة', 'skill_description': 'نسخ الحروف', 'min_age_months': 48},
    {'skill_group': 'مهارات ما قبل الكتابة', 'skill_description': 'نسخ مثلث', 'min_age_months': 60},
    {'skill_group': 'مهارات ما قبل الكتابة', 'skill_description': 'مسك القلم بثلاثة أصابع وتحريك الأصابع بدلاً من الرسغ', 'min_age_months': 60},
    {'skill_group': 'مهارات ما قبل الكتابة', 'skill_description': 'كتابة الأرقام من 1 إلى 10 بشكل مستقل', 'min_age_months': 60},
    {'skill_group': 'مهارات ما قبل الكتابة', 'skill_description': 'كتابة الحروف دون تقليد', 'min_age_months': 60},
    {'skill_group': 'مهارات ما قبل الكتابة', 'skill_description': 'الكتابة على السطر', 'min_age_months': 72},
    {'skill_group': 'مهارات ما قبل الكتابة', 'skill_description': 'التحكم في القلم', 'min_age_months': 72},
    {'skill_group': 'مهارات ما قبل الكتابة', 'skill_description': 'التحمل في مهام الكتابة', 'min_age_months': 72},
    {'skill_group': 'مهارات ما قبل الكتابة', 'skill_description': 'الكتابة بخط واضح', 'min_age_months': 84},
    {'skill_group': 'مهارات ما قبل الكتابة', 'skill_description': 'الحفاظ على وضوح الكتابة طوال القصة', 'min_age_months': 84},

    // Group 3: مهارات القص بالمقص (Scissor Skills)
    {'skill_group': 'مهارات القص بالمقص', 'skill_description': 'عمل قصّات بسيطة بالمقص', 'min_age_months': 24},
    {'skill_group': 'مهارات القص بالمقص', 'skill_description': 'قصّ الصور بشكل تقريبي', 'min_age_months': 36},
    {'skill_group': 'مهارات القص بالمقص', 'skill_description': 'القص على خط بشكل مستمر', 'min_age_months': 48},
    {'skill_group': 'مهارات القص بالمقص', 'skill_description': 'قصّ أشكال بسيطة', 'min_age_months': 60},
    {'skill_group': 'مهارات القص بالمقص', 'skill_description': 'تنفيذ أنشطة القص واللصق', 'min_age_months': 60},
    {'skill_group': 'مهارات القص بالمقص', 'skill_description': 'القص حول الأشكال بدقة', 'min_age_months': 72},

    // Group 4: مهارات الاعتماد على الذات (Self-Care Skills)
    {'skill_group': 'مهارات الاعتماد على الذات', 'skill_description': 'الأكل بشكل مستقل (مساعدة بسيطة ممكنة)', 'min_age_months': 12},
    {'skill_group': 'مهارات الاعتماد على الذات', 'skill_description': 'استخدام الملعقة للأكل', 'min_age_months': 12},
    {'skill_group': 'مهارات الاعتماد على الذات', 'skill_description': 'الإمساك بالكوب والشرب بدون مساعدة', 'min_age_months': 12},
    {'skill_group': 'مهارات الاعتماد على الذات', 'skill_description': 'الأكل بدون مساعدة', 'min_age_months': 24},
    {'skill_group': 'مهارات الاعتماد على الذات', 'skill_description': 'فتح أكياس السحاب (ziplock) والعلب وصناديق الغداء', 'min_age_months': 36},
    {'skill_group': 'مهارات الاعتماد على الذات', 'skill_description': 'تنسيق اليدين لتنظيف الأسنان أو تمشيط الشعر', 'min_age_months': 36},
    {'skill_group': 'مهارات الاعتماد على الذات', 'skill_description': 'اللبس بشكل مستقل (يشمل الأزرار الكبيرة، الجوارب، الأحذية) باستثناء الأربطة...', 'min_age_months': 36},
    {'skill_group': 'مهارات الاعتماد على الذات', 'skill_description': 'اللبس والخلع بشكل مستقل (ما عدا الأربطة)', 'min_age_months': 48},
    {'skill_group': 'مهارات الاعتماد على الذات', 'skill_description': 'استخدام السكين والشوكة للأطعمة اللينة', 'min_age_months': 60},
    {'skill_group': 'مهارات الاعتماد على الذات', 'skill_description': 'اللبس واستخدام الحمام بشكل مستقل', 'min_age_months': 72},
    {'skill_group': 'مهارات الاعتماد على الذات', 'skill_description': 'ربط أربطة الحذاء', 'min_age_months': 72},
    {'skill_group': 'مهارات الاعتماد على الذات', 'skill_description': 'استخدام السكين والشوكة لمعظم الأطعمة', 'min_age_months': 84},
  ];

  // قيم ROM القياسية
  static const Map<String, List<Map<String, dynamic>>> jointMotions = {
    'Shoulder': [
      {'motion': 'Flexion', 'ar': 'ثني', 'max': 180.0},
      {'motion': 'Extension', 'ar': 'بسط', 'max': 60.0},
      {'motion': 'Abduction', 'ar': 'تبعيد', 'max': 180.0},
      {'motion': 'Adduction', 'ar': 'تقريب', 'max': 45.0},
      {'motion': 'Internal Rotation', 'ar': 'تدوير داخلي', 'max': 70.0},
      {'motion': 'External Rotation', 'ar': 'تدوير خارجي', 'max': 90.0},
    ],
    'Elbow': [
      {'motion': 'Flexion', 'ar': 'ثني', 'max': 150.0},
      {'motion': 'Extension', 'ar': 'بسط', 'max': 10.0}, // للسماح بفرط البسط البسيط
      {'motion': 'Pronation', 'ar': 'كب', 'max': 80.0},
      {'motion': 'Supination', 'ar': 'بسط/لف خارجي', 'max': 90.0},
    ],
    'Wrist': [
      {'motion': 'Flexion', 'ar': 'ثني لأسفل', 'max': 80.0},
      {'motion': 'Extension', 'ar': 'بسط لأعلى', 'max': 70.0},
      {'motion': 'Radial Deviation', 'ar': 'انحراف شعاعي', 'max': 20.0},
      {'motion': 'Ulnar Deviation', 'ar': 'انحراف زندي', 'max': 45.0},
    ],
  };
}